### PR TITLE
Tx v3

### PR DESCRIPTION
**Pull request by why-not-try-calmer**
Renaming branch used in #27 as CI appears to dislike it.

### CODE REVIEW

**Comment by ponceta** [comment]
@why-not-try-calmer I've invited you to the maintain permission, I hope this enable you to run the tests/actions for Pull requests

**Comment by ponceta** [comment]
Looks like we have some informations missing :

INPUT_REPOSITORY value: .
INPUT_STATUS_OPTIONS: 
INPUT_FILE_PATTERN: .
INPUT_BRANCH value: tx-v3

I do not know if these are mandatory.

**Comment by why-not-try-calmer** [comment]
@ponceta Is it possible that the TX_TOKEN that this repo is using is not longer valid? I've just tried after hard-coding a personal API_TOKEN (which I deprecated immediately after the test) and it worked.

Also the [actions logs](https://github.com/qwat/docs/actions/runs/4042925826/jobs/6951226168) suggest that the migration to Tx v.3 per se works, but the workflow still chokes on this post-job "stefanzweifel/git-auto-commit-action@v4" step. I understand that the idea is to use this action to ensure the the config file generated by the Python script is saved to Github. But why is it necessary?

Removing this step would help, as it creates one more way the job can fail.

**Comment by ponceta** [comment]
@why-not-try-calmer thank you for this.

Please check with @m-kuhn or @olivierdalang for what is necessary. If a new TOKEN is required we can generate a new one from Transifex and store it into the gitHub secrets as before.

The simpler the better. ;)

**Comment by ponceta** [comment]
TX_TOKEN updated (in repository secrets) QWAT / DOCS

**Comment by m-kuhn** [comment]
superseded by #29

**Pull request closed without merging**
